export const BASE_URL =
  'https://opensea.io/assets/matic/0x22d5f9b75c524fec1d6619787e582644cd4d7422';

export const boosters = {
  crops: [
    {
      name: 'Easter Bunny',
      type: 'crop',
      description: ['+20% carrot'],
      currentPrice: 0,
      offerPrice: 0,
      url: '909',
      urlImg:
        'https://i.seadn.io/gcs/files/53a44b4ba601ab61e7bf2368dd37258a.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Victoria Sisters',
      type: 'crop',
      description: ['+20% pumpkin'],
      currentPrice: 0,
      offerPrice: 0,
      url: '432',
      urlImg:
        'https://i.seadn.io/gcs/files/1c2f23e736522b556b627701d07c9c4f.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Peeled Potato',
      type: 'crop',
      description: ['+20% potato'],
      currentPrice: 0,
      offerPrice: 0,
      url: '433',
      urlImg:
        'https://i.seadn.io/gcs/files/61edb0f1faad0caa36231058a75b5152.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Cabbage Boy',
      type: 'crop',
      description: ['+0.25 cabbage'],
      combos: [{ name: 'Cabbage Girl', effect: '+0.15 cabbage', buffs: true }],
      alerts: ['Karkinos has no effect with Cabbage Boy'],
      currentPrice: 0,
      offerPrice: 0,
      url: '434',
      urlImg:
        'https://i.seadn.io/gcs/files/02a0eacbf56270f822db210f8cdce4ad.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Cabbage Girl',
      type: 'crop',
      description: ['-50% cabbage production time'],
      combos: [{ name: 'Cabbage Boy', effect: '+0.15 cabbage' }],
      currentPrice: 0,
      offerPrice: 0,
      url: '435',
      urlImg:
        'https://i.seadn.io/gcs/files/7d3a80576797b264c0704e71629f3275.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Karkinos',
      type: 'crop',
      description: ['+0.1 cabbage'],
      alerts: ['Karkinos has no effect with Cabbage Boy'],
      currentPrice: 0,
      offerPrice: 0,
      url: '455',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Mysterious Parsnip',
      type: 'crop',
      description: ['-50% parsnip production time'],
      currentPrice: 0,
      offerPrice: 0,
      url: '418',
      urlImg:
        'https://i.seadn.io/gcs/files/50c63763c89010e5b4dd1f8bbe71f3a8.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Golden Cauliflower',
      type: 'crop',
      description: ['+200% cauliflower'],
      currentPrice: 0,
      offerPrice: 0,
      url: '410',
      urlImg:
        'https://i.seadn.io/gcs/files/1c272d6cb5ff87fc19fb985b292a9323.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Carrot Sword',
      type: 'crop',
      description: ['increases the chance of finding a mutant crop'],
      currentPrice: 0,
      offerPrice: 0,
      url: '419',
      urlImg:
        'https://i.seadn.io/gcs/files/4d9907e9db06bd21018690a44920edf8.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Lunar Calendar',
      type: 'crop',
      description: ['-10% crop production time'],
      currentPrice: 0,
      offerPrice: 0,
      url: '448',
      urlImg:
        'https://i.seadn.io/gcs/files/46c3891d1c0b7a64bbe295bea122a9c3.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Nancy',
      type: 'crop',
      description: ['-15% crop production time'],
      currentPrice: 0,
      offerPrice: 0,
      url: '420',
      urlImg:
        'https://i.seadn.io/gcs/files/1f3bc72b9fef92024deadbce39cb44c2.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Scarecrow',
      type: 'crop',
      description: ['-15% crop production time', '+20% crop'],
      currentPrice: 0,
      offerPrice: 0,
      url: '404',
      urlImg:
        'https://i.seadn.io/gcs/files/c01d91c4cb22d12f54ca2b9cad011f3a.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Kuebiko',
      type: 'crop',
      description: ['-15% crop production time', '+20% crop', 'free seeds'],
      currentPrice: 0,
      offerPrice: 0,
      url: '421',
      urlImg:
        'https://i.seadn.io/gcs/files/09aa31be98562261634f0033d4314d02.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
  ],
  resources: [
    {
      name: 'Tiki Totem',
      type: 'resource',
      description: ['+0.1 wood'],
      buffs: ['wood'],
      buffsType: ['boost'],
      currentPrice: 0,
      offerPrice: 0,
      url: '447',
      urlImg:
        'https://i.seadn.io/gcs/files/98850f52a5b332a61fec3513117596af.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Wood Nymph Wendy',
      type: 'resource',
      description: ['+0.2 wood'],
      buffs: ['wood'],
      buffsType: ['boost'],
      currentPrice: 0,
      offerPrice: 0,
      url: '436',
      urlImg:
        'https://i.seadn.io/gcs/files/46bc4e07fbe6172e0be04836ec370e3a.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Rock Golem',
      type: 'resource',
      description: ['10% to get 3x stone'],
      buffs: ['stone'],
      buffsType: ['boost'],
      currentPrice: 0,
      offerPrice: 0,
      url: '427',
      urlImg:
        'https://i.seadn.io/gcs/files/b973bd890a88f216477829e484e9d2d2.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Iron Idol',
      type: 'resource',
      description: ['+1 iron'],
      buffs: ['iron'],
      buffsType: ['boost'],
      currentPrice: 0,
      offerPrice: 0,
      url: '454',
      urlImg:
        'https://i.seadn.io/gcs/files/cc4bedce9673c21f78d1a635c025f07a.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Woody the Beaver',
      type: 'resource',
      description: ['+20% wood'],
      buffs: ['wood'],
      buffsType: ['boost'],
      currentPrice: 0,
      offerPrice: 0,
      url: '415',
      urlImg:
        'https://i.seadn.io/gcs/files/a2ec46780fef483cb4f5ecb10f9ba532.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Apprentice Beaver',
      type: 'resource',
      description: ['+20% wood', '-50% tree recovery time'],
      buffs: ['wood'],
      buffsType: ['boost', 'cooldown'],
      currentPrice: 0,
      offerPrice: 0,
      url: '416',
      urlImg:
        'https://i.seadn.io/gcs/files/e6cab0fafdb214f7adf0da6b12a856a7.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Foreman Beaver',
      type: 'resource',
      description: [
        '+20% wood',
        '-50% tree recovery time',
        'cut trees without axe',
      ],
      buffs: ['wood'],
      buffsType: ['boost', 'cooldown', 'special'],
      currentPrice: 0,
      offerPrice: 0,
      url: '417',
      urlImg:
        'https://i.seadn.io/gcs/files/70f6c4e86553901297e4190b1a3b22f0.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Tunnel Mole',
      type: 'resource',
      description: ['+25% stone'],
      buffs: ['stone'],
      buffsType: ['boost'],
      currentPrice: 0,
      offerPrice: 0,
      url: '428',
      urlImg:
        'https://i.seadn.io/gcs/files/c343b23545122aacc48abc95a1058e87.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Rocky the Mole',
      type: 'resource',
      description: ['+25% iron'],
      buffs: ['iron'],
      buffsType: ['boost'],
      currentPrice: 0,
      offerPrice: 0,
      url: '429',
      urlImg:
        'https://i.seadn.io/gcs/files/66016e65cfeaf23b1418f56aedb7d25b.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Nugget',
      type: 'resource',
      description: ['+25% gold'],
      buffs: ['gold'],
      buffsType: ['boost'],
      currentPrice: 0,
      offerPrice: 0,
      url: '430',
      urlImg:
        'https://i.seadn.io/gcs/files/0d42db9656d796cde7f85a3e4fb84f06.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
  ],
  chickens: [
    {
      name: 'Fat Chicken',
      type: 'chicken',
      description: [
        'Reduce wheat requirement for chickens 10%',
        '+0.001 chance to get a mutant chicken',
      ],
      buffs: ['egg'],
      buffsType: ['special'],
      currentPrice: 0,
      offerPrice: 0,
      url: '611',
      urlImg:
        'https://i.seadn.io/gcs/files/c4f8dcd6c09ae7043e7ad224d2a36238.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Speed Chicken',
      type: 'chicken',
      description: [
        '-10% egg production time',
        '+0.001 chance to get a mutant chicken',
      ],
      buffs: ['egg'],
      buffsType: ['cooldown'],
      currentPrice: 0,
      offerPrice: 0,
      url: '610',
      urlImg:
        'https://i.seadn.io/gcs/files/c4857a1b52264cf2917c73ef544aa835.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Rich Chicken',
      type: 'chicken',
      description: ['+10% egg', '+0.001 chance to get a mutant chicken'],
      buffs: ['egg'],
      buffsType: ['boost'],
      currentPrice: 0,
      offerPrice: 0,
      url: '612',
      urlImg:
        'https://i.seadn.io/gcs/files/bc6e8521ddd81769ef3f434b9c44a122.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Rooster',
      type: 'chicken',
      description: ['2x chance to get mutant chicken'],
      buffs: ['egg'],
      buffsType: ['special'],
      currentPrice: 0,
      offerPrice: 0,
      url: '613',
      urlImg:
        'https://i.seadn.io/gcs/files/d699b51b5297d0a9c53d12b0fe812f67.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Undead Rooster',
      type: 'chicken',
      description: ['+10% egg'],
      buffs: ['egg'],
      buffsType: ['boost'],
      currentPrice: 0,
      offerPrice: 0,
      url: '1114',
      urlImg:
        'https://i.seadn.io/gcs/files/c4561c51b1c7450f1e7e60f27cb914d5.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Chicken Coop',
      type: 'chicken',
      description: ['+200% egg', '+5 chicken per hen'],
      buffs: ['egg'],
      buffsType: ['boost', 'special'],
      currentPrice: 0,
      offerPrice: 0,
      url: '408',
      urlImg:
        'https://i.seadn.io/gcs/files/a530a92ceb36e887bc32263095fd1f65.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Gold Egg',
      type: 'chicken',
      description: ['Feed chickens without wheat'],
      buffs: ['egg'],
      buffsType: ['special'],
      currentPrice: 0,
      offerPrice: 0,
      url: '409',
      urlImg:
        'https://i.seadn.io/gcs/files/397bf15b425228bf095c01f08286e29a.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
  ],
  fruits: [
    {
      name: 'Lady Bug',
      type: 'fruit',
      description: ['+0.25 apple'],
      buffs: ['apple'],
      buffsType: ['boost'],
      currentPrice: 0,
      offerPrice: 0,
      url: '442',
      urlImg:
        'https://i.seadn.io/gcs/files/e59d0681c41fce422d2f91b8c3d5e0bd.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Squirrel Monkey',
      type: 'fruit',
      description: ['-50% orange production time'],
      buffs: ['orange'],
      buffsType: ['cooldown'],
      currentPrice: 0,
      offerPrice: 0,
      url: '443',
      urlImg:
        'https://i.seadn.io/gcs/files/774f8a0ba8c30eb9c6fb9271af18baef.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Black Bearry',
      type: 'fruit',
      description: ['+1 blueberry'],
      buffs: ['blueberry'],
      buffsType: ['boost'],
      currentPrice: 0,
      offerPrice: 0,
      url: '444',
      urlImg:
        'https://i.seadn.io/gcs/files/5868ba605a2350b8185c2380b446bcd4.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Immortal Pear',
      type: 'fruit',
      description: ['+1 bonus harvest'],
      buffs: ['fruit'],
      buffsType: ['special'],
      currentPrice: 0,
      offerPrice: 0,
      url: '441',
      urlImg:
        'https://i.seadn.io/gcs/files/5679558b3d89fc683d13cd5a26a34056.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: false,
    },
  ],
  xp: [
    {
      name: 'Maneki Neko',
      type: 'xp',
      description: ['+1 food each 24 hours'],
      buffs: ['xp'],
      buffsType: ['special'],
      currentPrice: 0,
      offerPrice: 0,
      url: '446',
      urlImg:
        'https://i.seadn.io/gcs/files/d0ec6cb215da3190f2e70d6f2a3e8b1b.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Observatory',
      type: 'xp',
      description: ['+5% xp'],
      buffs: ['xp'],
      buffsType: ['boost'],
      currentPrice: 0,
      offerPrice: 0,
      url: '911',
      urlImg:
        'https://i.seadn.io/gcs/files/688137bb65b5a7e02e844706c6c7bad7.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
  ],
  others: [
    {
      name: 'Christmas Tree',
      type: 'other',
      description: ['give 1 airdrop each year'],
      currentPrice: 0,
      offerPrice: 0,
      url: '403',
      urlImg:
        'https://i.seadn.io/gcs/files/abe2715724a991fa0f829ec005317d79.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Heart of Davy Jones',
      type: 'other',
      description: ['+25 holes to dig in Treasure Island'],
      currentPrice: 0,
      offerPrice: 0,
      url: '450',
      urlImg:
        'https://i.seadn.io/gcs/files/82f41b2dd65bfd5fd1ad7a79dbd1f118.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Treasure Map',
      type: 'other',
      description: ['+20% profit from beach bounty'],
      currentPrice: 0,
      offerPrice: 0,
      url: '449',
      urlImg:
        'https://i.seadn.io/gcs/files/117c37bfa4080d2cf065db5ed26c3f7b.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: false,
    },
  ],
};

export const decoratives = {
  misc: [
    {
      name: 'Beach Ball',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '1242',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Blossom Tree',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '453',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Christmas Snow Globe',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '1219',
      urlImg:
        'https://i.seadn.io/gcs/files/7d5bb070f084f6d72ba78989252e9baa.gif?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Farm Cat',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '405',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Farm Dog',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '406',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Farmer Bath',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '423',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Flamingo',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '452',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Fountain',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '',
      urlImg: '414',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Gnome',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '407',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Goblin Crown',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '413',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Golden Bonsai',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '426',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Heart Balloons',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '451',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Homeless Tent',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '424',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Mysterious Head',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '425',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Nyon Statue',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '422',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Palm Tree',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '1241',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Potato Statue',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '402',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Sunflower Coin',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '1226',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Sunflower Rock',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '412',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Sunflower Statue',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '401',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Sunflower Tombstone',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '411',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'T-Rex Skull',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '1225',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'War Skull',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '1112',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'War Tombstone',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '1113',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Wicker Man',
      type: 'misc',
      currentPrice: 0,
      offerPrice: 0,
      url: '431',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
  ],
  bears: [
    {
      name: 'Abandoned Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1223',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Angel Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1207',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Badass Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '',
      urlImg: '1208',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Basic Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1204',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Brilliant Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1210',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Chef Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1205',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Christmas Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1217',
      urlImg:
        'https://i.seadn.io/gcs/files/be13471d2d50154164e595cb977719e7.png?auto=format&w=384',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Classy Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1211',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Collectible Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1221',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Construction Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1206',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Cyborg Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1222',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Farmer Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1212',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Lifeguard Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1229',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Pirate Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1233',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Rainbow Artist Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1218',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Rich Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1214',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Snorkel Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1230',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Sunflower Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1213',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Turtle Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1224',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Valentine Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1240',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Whale Bear',
      type: 'bear',
      currentPrice: 0,
      offerPrice: 0,
      url: '1233',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
  ],
  flags: [
    {
      name: 'Algerian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '836',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'American Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '826',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Argentinian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '839',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Australian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '801',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Belgian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '802',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Brazilian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '803',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'British Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '830',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Chinese Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '804',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Colombian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '842',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Dominican Republic Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '838',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Dutch Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '814',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'French Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '806',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Finnish Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '805',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'German Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '807',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Goblin Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '834',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Indian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '809',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Indonesian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '808',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Iranian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '810',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Italian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '811',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Japanese Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '812',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Lithuanian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '840',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Malaysian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '841',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Mexican Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '837',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Moroccan Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '813',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Philippine Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '815',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Pirate Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '835',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Polish Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '816',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Portuguese Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '817',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Rainbow Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '833',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Russian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '818',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Romanian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '832',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Saudi Arabian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '819',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Singaporean Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '829',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Sierra Leone Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '831',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'South Korean Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '820',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Spanish Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '821',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Sunflower Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '822',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Thai Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '823',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Turkish Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '824',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Ukrainian Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '825',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
    {
      name: 'Vietnamese Flag',
      type: 'flag',
      currentPrice: 0,
      offerPrice: 0,
      url: '827',
      urlImg: '',
      collection: 'Sunflower Land Collectibles',
      isSelling: true,
    },
  ],
};
